name: Notify slack
on: watch
jobs:
  star-notify:
    name: Notify slack on star
    runs-on: ubuntu-latest
    steps:
    - name: Notify slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
        run: STAR="$(curl -s https://github.com/layer5io/image-hub | nokogiri -e 'puts $_.search('\''a'\'').text' | sed -n 95p | awk '{print $1}')"
        args: '{\"channel\":\"CSK7N9TGX\",\"text\":\"Someone just starred Image Hub! (https://github.com/layer5io/image-hub/stargazers)\"}'
        command: echo "Now at $STAR stars."

